Repository InternLM/InternLM, pull requests merged in 2023-11, with the labels that each got.

#460 fix(readme): update README with original weight download link
  README.md
Labels: documentation

#467 fix(tools): fix streaming_chat and update docs
  README-ja-JP.md
  README-zh-Hans.md
  README.md
  tools/tokenizer.py
  tools/transformers/convert2hf.py
  tools/transformers/internlm_model/__init__.py
  tools/transformers/internlm_model/configuration_internlm.py
  tools/transformers/internlm_model/modeling_internlm.py
  tools/transformers/internlm_model/tokenization_internlm.py
Labels: Bug, documentation

#474 fix(readme): fix model_path in readme
  README-ja-JP.md
  README-zh-Hans.md
  README.md
Labels: Bug, documentation

#470 feat(tools): support dynamic ntk rope in transformers
  tools/transformers/internlm_model/configuration_internlm.py
  tools/transformers/internlm_model/modeling_internlm.py
Labels: enhancement

#475 fix(data): broadcast list when walking dataset folders to avoid problems
  internlm/data/packed_dataset.py
Labels: Bug, enhancement

#477 feat(data): walk folder to get dataset_type_ids_map
  internlm/data/packed_dataset.py
  internlm/data/utils.py
  internlm/train/training_internlm.py
Labels: Bug, enhancement

#471 fix(tools): set bos, eos, pad in convert2hf to fix improper generation
  tools/transformers/convert2hf.py
Labels: Bug

#480 feat(doc): add dynamic ntk example
  doc/aux_ materials/long_text_example.txt
  doc/imgs/dynamic_ntk_answer.png
  doc/usage.md
Labels: documentation

#479 feat(doc): add torch_dtype to examples in README
  README-ja-JP.md
  README-zh-Hans.md
  README.md
Labels: documentation

#481 fix(metric): use float32 to compute ppl
  internlm/model/metrics.py
Labels: Bug, enhancement

#486 feat(ckpt): save ckpt when reach total step count
  internlm/utils/model_checkpoint.py
Labels: enhancement

#489 fix(data): fix dataset types when using random dataset
  .gitignore
  internlm/train/training_internlm.py
Labels: Bug

#491 fix(alert): send exception of all ranks
  configs/7B_sft.py
  internlm/initialize/launch.py
  internlm/monitor/monitor.py
Labels: Bug

#498 feat(train): update get_train_data_loader to make logic clearer
  internlm/train/training_internlm.py
Labels: enhancement

#484 Feat(QA): check only forward logits
  tests/test_core/test_pipeline.py
  tests/test_model/test_embedding.py
  tests/test_model/test_model_internlm.py
  tests/test_model/test_norm.py
Labels: enhancement

#493 feat(train): support rampup batch_size
  configs/7B_sft.py
  internlm/core/context/parallel_context.py
  internlm/core/scheduler/base_scheduler.py
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/initialize/launch.py
  internlm/utils/evaluation.py
  tests/test_core/__init__.py
  tests/test_core/test_pipeline.py
  tests/test_core/utils.py
  tests/test_data/test_batch_sampler.py
Labels: enhancement

#496 feat(seed): set global seed for every model initialization
  internlm/initialize/launch.py
  internlm/model/modeling_internlm.py
Labels: enhancement

#495 fix(timeout): larger timeout
  internlm/utils/common.py
  internlm/utils/timeout.py
Labels: enhancement

#507 feat(doc): add GPU memory info for 7B & 20B models
  doc/en/train_performance.md
  doc/train_performance.md
Labels: documentation

#515 fix/feat: small fix and enhancement
  configs/7B_sft.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/initialize/launch.py
  internlm/utils/evaluation.py
  internlm/utils/gputest.py
  tests/test_training/train_CI.py
  train.py
Labels: Bug, enhancement
