Repository InternLM/InternLM, pull requests merged in 2023-09, with the labels that each got.

#265 fix(doc/code-docs): autodoc shown error
  doc/code-docs/requirements.txt
  doc/code-docs/source/conf.py
Labels: Bug

#259 feat(ckpt): checkpoint bug fixes and feature enhancements.
  configs/7B_sft.py
  doc/en/usage.md
  doc/usage.md
  internlm/core/trainer.py
  internlm/initialize/launch.py
  internlm/initialize/legacy/__init__.py
  internlm/initialize/legacy/launch.py
  internlm/solver/optimizer/__init__.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/utils/model_checkpoint.py
  internlm/utils/storage_manager.py
  tests/test_utils/common_fixture.py
  tests/test_utils/test_model_checkpoint.py
  tests/test_utils/test_storage_manager.py
  train.py
Labels: enhancement

#276 fix/broadcast should not in commu stream
  internlm/solver/optimizer/hybrid_zero_optim.py
Labels: Bug

#271 fix(model): set tensor parallel attribute for mlp
  internlm/model/linear.py
  internlm/model/modeling_internlm.py
Labels: Bug

#275 feat(monitor): add light monitor
  internlm/initialize/launch.py
  internlm/monitor/__init__.py
  internlm/monitor/alert.py
  internlm/train/training_internlm.py
Labels: enhancement

#266 fix(core/context): use dummy mode to generate random numbers in model construction
  internlm/core/context/parallel_context.py
  internlm/core/context/process_group_initializer.py
  internlm/train/training_internlm.py
Labels: Bug

#272 docs(*): add documentation and reST files for readthedocs
  doc/code-docs/requirements.txt
  doc/code-docs/source/checkpoint.rst
  doc/code-docs/source/conf.py
  doc/code-docs/source/example/30B_demo.rst
  doc/code-docs/source/example/7B_demo.rst
  doc/code-docs/source/example/index.rst
  doc/code-docs/source/index.rst
  doc/code-docs/source/initialize.rst
  doc/code-docs/source/install.md
  doc/code-docs/source/monitor.rst
  doc/code-docs/source/parallel.rst
  doc/code-docs/source/profiler.rst
  doc/code-docs/source/qa.rst
  doc/code-docs/source/training.rst
  doc/code-docs/source/usage.md
  doc/en/install.md
  doc/en/usage.md
  doc/imgs/pipeline_schedule.png
  doc/imgs/sequence_parallel.png
  doc/imgs/tensor_parallel.png
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/core/trainer.py
  internlm/initialize/initialize_trainer.py
  internlm/initialize/launch.py
  internlm/model/modeling_internlm.py
  internlm/monitor/monitor.py
  internlm/train/training_internlm.py
Labels: documentation

#289 docs(doc/code-docs): support zh cn readthedocs
  doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
  doc/code-docs/locales/en/LC_MESSAGES/example/30B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/7B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/index.po
  doc/code-docs/locales/en/LC_MESSAGES/index.po
  doc/code-docs/locales/en/LC_MESSAGES/initialize.po
  doc/code-docs/locales/en/LC_MESSAGES/install.po
  doc/code-docs/locales/en/LC_MESSAGES/monitor.po
  doc/code-docs/locales/en/LC_MESSAGES/parallel.po
  doc/code-docs/locales/en/LC_MESSAGES/profiler.po
  doc/code-docs/locales/en/LC_MESSAGES/qa.po
  doc/code-docs/locales/en/LC_MESSAGES/training.po
  doc/code-docs/locales/en/LC_MESSAGES/usage.po
  doc/code-docs/source/checkpoint.rst
  doc/code-docs/source/conf.py
  doc/code-docs/source/example/30B_demo.rst
  doc/code-docs/source/example/7B_demo.rst
  doc/code-docs/source/example/index.rst
  doc/code-docs/source/index.rst
  doc/code-docs/source/initialize.rst
  doc/code-docs/source/install.md
  doc/code-docs/source/monitor.rst
  doc/code-docs/source/parallel.rst
  doc/code-docs/source/profiler.rst
  doc/code-docs/source/qa.rst
  doc/code-docs/source/training.rst
  doc/code-docs/source/usage.md
  doc/en/usage.md
  doc/install.md
  doc/usage.md
Labels: documentation

#286 Feat(utils): add timeout warpper
  internlm/core/context/parallel_context.py
  internlm/core/context/process_group_initializer.py
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/initialize/launch.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/train/training_internlm.py
  internlm/utils/logger.py
  internlm/utils/model_checkpoint.py
  internlm/utils/timeout.py
  tests/test_utils/common_fixture.py
  tests/test_utils/test_timeout.py
Labels: enhancement

#277 Feat/sync grad use async op
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/solver/optimizer/store.py
  internlm/solver/optimizer/utils.py
Labels: enhancement

#273 feat(fsdp): add training option for fsdp
  doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
  doc/code-docs/locales/en/LC_MESSAGES/example/30B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/7B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/index.po
  doc/code-docs/locales/en/LC_MESSAGES/index.po
  doc/code-docs/locales/en/LC_MESSAGES/initialize.po
  doc/code-docs/locales/en/LC_MESSAGES/install.po
  doc/code-docs/locales/en/LC_MESSAGES/monitor.po
  doc/code-docs/locales/en/LC_MESSAGES/parallel.po
  doc/code-docs/locales/en/LC_MESSAGES/profiler.po
  doc/code-docs/locales/en/LC_MESSAGES/qa.po
  doc/code-docs/locales/en/LC_MESSAGES/training.po
  doc/code-docs/locales/en/LC_MESSAGES/usage.po
  doc/code-docs/requirements.txt
  doc/code-docs/source/checkpoint.rst
  doc/code-docs/source/conf.py
  doc/code-docs/source/example/30B_demo.rst
  doc/code-docs/source/example/7B_demo.rst
  doc/code-docs/source/example/index.rst
  doc/code-docs/source/index.rst
  doc/code-docs/source/initialize.rst
  doc/code-docs/source/install.md
  doc/code-docs/source/monitor.rst
  doc/code-docs/source/parallel.rst
  doc/code-docs/source/profiler.rst
  doc/code-docs/source/qa.rst
  doc/code-docs/source/training.rst
  doc/code-docs/source/usage.md
  doc/en/install.md
  doc/en/usage.md
  doc/imgs/pipeline_schedule.png
  doc/imgs/sequence_parallel.png
  doc/imgs/tensor_parallel.png
  doc/install.md
  doc/usage.md
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/core/trainer.py
  internlm/initialize/initialize_trainer.py
  internlm/initialize/launch.py
  internlm/model/modeling_internlm.py
  internlm/monitor/monitor.py
  internlm/train/training_internlm.py
Labels: enhancement

#294 fix: fix the bug to do bcast in a stream
  internlm/solver/optimizer/hybrid_zero_optim.py
Labels: Bug

#297 feat: add runtime diag
  configs/7B_sft.py
  internlm/initialize/launch.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/solver/optimizer/utils.py
  internlm/train/training_internlm.py
  internlm/utils/gputest.py
  internlm/utils/megatron_timers.py
  train.py
Labels: enhancement

#298 fix(ckpt): fix snapshot none load error and remove file lock
  internlm/utils/model_checkpoint.py
  tests/test_utils/common_fixture.py
  tests/test_utils/test_model_checkpoint.py
Labels: Bug

#299 fix(convert2hf.py): fix the `rotary_emb.inv_freq` KeyError
  tools/transformers/convert2hf.py
Labels: Bug

#301 docs(doc/code-docs): update quickstart usage
  doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
  doc/code-docs/locales/en/LC_MESSAGES/usage.po
  doc/en/usage.md
  doc/usage.md
  internlm/utils/model_checkpoint.py
Labels: documentation

#303 feat: add optimizer_unitest
  tests/test_solver/test_optimizer.py
Labels: enhancement

#313 feat(tools): support openai api
  tools/README.md
  tools/README_EN.md
  tools/openai_api.py
Labels: enhancement

#315 fix(tools): fix yield bug in stream_chat
  tools/transformers/modeling_internlm.py
Labels: Bug

#317 test(ci_scripts): move ci env
  .github/workflows/demo_in_readme.yaml
  ci_scripts/common/variables.sh
  ci_scripts/data/tokenizer_alpaca.sh
  ci_scripts/data/tokenizer_chinese.sh
  ci_scripts/model/convert_to_hf.sh
  ci_scripts/train/load_ckpt.sh
  ci_scripts/train/slurm_train.sh
  ci_scripts/train/torchrun.sh
Labels: enhancement

#304 test(tests/test_training): add training e2e tests for loss spike and loss accuracy
  .github/workflows/e2e_test.yaml
  configs/7B_sft.py
  internlm/initialize/launch.py
  tests/test_training/__init__.py
  tests/test_training/test_loss.py
Labels: enhancement

#321 feat(linear): optimize mlp by using jit
  internlm/model/linear.py
  internlm/model/modeling_internlm.py
  internlm/model/utils.py
Labels: enhancement

#326 Feat(PythonGC): Do garbage collection manually
  internlm/initialize/launch.py
  internlm/utils/gputest.py
Labels: Bug

#324 feat(.github/workflows): update ci e2e tests and add ci unit tests
  .github/workflows/e2e_test.yaml
  .github/workflows/weekly_test.yaml
  tests/test_training/test_loss.py
Labels: enhancement

#311 feat(doc/code-docs): add checkpoint save/load usage doc
  doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
  doc/code-docs/source/checkpoint.rst
  doc/imgs/ckpt_path_format_CN.png
Labels: documentation

#359 fix(storage): fix try_get_storage_backend
  internlm/utils/model_checkpoint.py
  internlm/utils/storage_manager.py
  tests/test_utils/test_storage_manager.py
Labels: Bug

#338 fix(monitor): add volc and aliyun jobid
  internlm/monitor/utils.py
Labels: enhancement

#352 doc(monitor): add light monitoring doc
  doc/code-docs/locales/en/LC_MESSAGES/monitor.po
  doc/code-docs/source/monitor.rst
  internlm/monitor/alert.py
Labels: documentation

#320 feat(numa): bind numa if possible
  experiment/Dockerfile-centos
  experiment/Dockerfile-ubuntu
  internlm/initialize/__init__.py
  internlm/initialize/launch.py
  requirements/runtime.txt
Labels: enhancement

#182 feat(moe): add moe module
  configs/7B_MoE4_sft.py
  internlm/core/context/parallel_context.py
  internlm/core/context/process_group_initializer.py
  internlm/core/naive_amp.py
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/core/trainer.py
  internlm/initialize/launch.py
  internlm/model/__init__.py
  internlm/model/modeling_moe.py
  internlm/model/moe.py
  internlm/model/utils.py
  internlm/moe/experts.py
  internlm/moe/sharded_moe.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/solver/optimizer/utils.py
  internlm/train/training_internlm.py
  internlm/train/utils.py
  internlm/utils/evaluation.py
  internlm/utils/model_checkpoint.py
  internlm/utils/parallel.py
  internlm/utils/timeout.py
  tests/test_training/test_loss.py
  tests/test_utils/common_fixture.py
  train.py
Labels: enhancement

#374 docs(doc): add tf32 docs
  doc/code-docs/locales/en/LC_MESSAGES/mixed_precision.po
  doc/code-docs/source/mixed_precision.rst
  doc/imgs/tf32.png
Labels: documentation

#376 feat(moe): add local data parallel support for experts
  internlm/core/context/parallel_context.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/solver/optimizer/store.py
  internlm/train/training_internlm.py
  internlm/utils/model_checkpoint.py
  internlm/utils/parallel.py
Labels: enhancement

#380 Doc(config): add auto_resume annotation into example config
  configs/7B_sft.py
Labels: documentation
