Repository InternLM/InternLM, pull requests merged in 2023-12, with the labels that each got.

#520 feat(storage): use multipart upload when using oss
  internlm/initialize/launch.py
  internlm/utils/model_checkpoint.py
  internlm/utils/storage_manager.py
  tests/test_utils/common_fixture.py
  tests/test_utils/test_storage_manager.py
Labels: enhancement

#528 fix(model): add IS_SEQUENCE_PARALLEL check for norm module
  internlm/train/training_internlm.py
  internlm/utils/parallel.py
Labels: enhancement

#519 feat(grad_norm): vocab grad norm profiling
  internlm/initialize/launch.py
  internlm/solver/optimizer/hybrid_zero_optim.py
  internlm/solver/optimizer/utils.py
  internlm/train/training_internlm.py
  train.py
Labels: enhancement

#516 fix(data): fix the unpack for type_ids when use_flash_attn=False
  internlm/data/utils.py
  internlm/train/training_internlm.py
Labels: Bug

#527 fix(storage): unify the name of AK and SK
  internlm/utils/storage_manager.py
Labels: enhancement

#530 fix(test): fix type_ids unpack bug
  tests/test_data/test_batch_sampler.py
Labels: Bug

#532 feat(model): support llama model with checkpoint loading
  configs/7B_sft.py
  internlm/model/__init__.py
  internlm/model/modeling_llama.py
  internlm/utils/model_checkpoint.py
  tools/transformers/internlm_model/modeling_internlm.py
Labels: enhancement

#533 fix(metric): add metric dtype control
  configs/7B_MoE4_sft.py
  configs/7B_sft.py
  internlm/model/metrics.py
Labels: enhancement

#529 feat(ckpt): support auto resume in Volc and Ali
  internlm/utils/model_checkpoint.py
  internlm/utils/storage_manager.py
Labels: enhancement

#538 fix(pp): fix no-packed dataset load micro batch error
  internlm/core/engine.py
  internlm/core/scheduler/base_scheduler.py
  internlm/core/scheduler/no_pipeline_scheduler.py
  internlm/core/scheduler/pipeline_scheduler.py
  internlm/utils/common.py
  tests/test_data/test_batch_sampler.py
Labels: enhancement

#539 fix(model): change model_type `LLAMA` to `LLAMA2`
  internlm/model/modeling_llama.py
  internlm/utils/model_checkpoint.py
  internlm/utils/registry.py
Labels: Bug, enhancement

#537 doc(readme): update 7b/20b chat model information
  .github/workflows/demo_in_readme.yaml
  .pre-commit-config.yaml
  .pylintrc
  README-ja-JP.md
  README-zh-Hans.md
  README.md
  doc/code-docs/locales/en/LC_MESSAGES/checkpoint.po
  doc/code-docs/locales/en/LC_MESSAGES/example/30B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/7B_demo.po
  doc/code-docs/locales/en/LC_MESSAGES/example/index.po
  doc/code-docs/locales/en/LC_MESSAGES/index.po
  doc/code-docs/locales/en/LC_MESSAGES/initialize.po
  doc/code-docs/locales/en/LC_MESSAGES/install.po
  doc/code-docs/locales/en/LC_MESSAGES/monitor.po
  doc/code-docs/locales/en/LC_MESSAGES/parallel.po
  doc/code-docs/locales/en/LC_MESSAGES/profiler.po
  doc/code-docs/locales/en/LC_MESSAGES/qa.po
  doc/code-docs/locales/en/LC_MESSAGES/training.po
  doc/code-docs/locales/en/LC_MESSAGES/usage.po
  doc/code-docs/requirements.txt
  doc/code-docs/source/example/30B_demo.rst
  doc/code-docs/source/example/7B_demo.rst
  doc/code-docs/source/initialize.rst
  doc/code-docs/source/install.md
  doc/code-docs/source/parallel.rst
  doc/code-docs/source/qa.rst
  doc/code-docs/source/training.rst
  doc/code-docs/source/usage.md
  doc/en/install.md
  doc/en/train_performance.md
  doc/install.md
  doc/train_performance.md
  docker.Makefile
  docker/Dockerfile-centos
  docker/Dockerfile-ubuntu
  experiment/Dockerfile-centos
  experiment/Dockerfile-ubuntu
  experiment/README-CN.md
  experiment/README-EN.md
  requirements/runtime.txt
  requirements/torch.txt
  tools/pal_inference.py
  tools/transformers/README-zh-Hans.md
  tools/transformers/README.md
  tools/transformers/configuration_internlm.py
  tools/transformers/convert2hf.py
  tools/transformers/interface.py
  tools/transformers/intern_moss_example.py
  tools/transformers/internlm_sft_on_moss.py
  tools/transformers/modeling_internlm.py
  tools/transformers/tokenization_internlm.py
Labels: documentation

#542 fix(model): add ckpt_type constraint when loading ckpts
  internlm/utils/model_checkpoint.py
Labels: enhancement

#554 fix(readme): fix deprecated model path in code examples
  README-ja-JP.md
  README-zh-Hans.md
  README.md
Labels: documentation

#555 fix(tools): set `add_eos_token=True` in tokenizer.py
  tools/tokenizer.py
Labels: Bug, enhancement

#560 fix(chat): fix stream_chat in modeling_internlm(hf) to avoid decode error
  tools/transformers/modeling_internlm.py
Labels: Bug

#549 feat(logger): add tensorboard key value buffer
  configs/7B_sft.py
  internlm/initialize/launch.py
  internlm/utils/writer.py
  train.py
Labels: enhancement

#557 fix(metrics): remove redundant cuda memory in metric calculations
  internlm/model/metrics.py
Labels: Bug
